let mic = document.getElementById("mic");
let chatareamain = document.querySelector('.chatarea-main');
let chatareaouter = document.querySelector('.chatarea-outer');

let hi=["hello", "Hi "]
let intro = ["Hello, I am Jarvis", "Hi, I am a Jarvis", "Hello, My name is Jarvis"];
let help = ["How may i assist you?","How can i help you?","What i can do for you?"];
let greetings = ["i am good you little piece of love", "i am fine, what about you", "don't want to talk", "i am good"];
let hobbies = ["i love to talk with humans", "i like to make friends like you", "i like cooking"];
let pizzas = ["which type of pizza do you like?", "i can make a pizza for you", "i would love to make a pizza for you", "would you like cheese pizza?"];
let thank = ["Most welcome","Not an issue","Its my pleasure","Mention not"];
let closing = ['Ok bye-bye','As you wish, bye take-care','Bye-bye, see you soon..']
let information = ["Hi, I am a Jarvis . I am a friendly voice assistant , I am coded by Om Wadgaonkar and ui interface desing is done by Rajveer Perdesi .  I am made for science exhibition . I am builded up using javascript in visual studio code, my goal is to assist you and chat with you to boost your  knowledge and save your time .I hope you like my service."];
let song =["sorry i cant , my voice is very bad"]
let ok =["ok"]
let live=["I live inside this computer made by genius humans"]
let game=["My favourite game is foodball! but I never got chance to play it <br>:(<br /> "]
let videogame=["I like Gta 5 , Minecraft and Asasian creed valhala"]
let bhurjkhalfa=["burj khalifa is building with 828 metres hieght (2,716.5 feet) and more than 160 stories, Burj Khalifa holds the following records: Tallest building in the world." ]
let eiffel=["Eiffel Tower is  300 metres (984 feet) high. It rests on a base that is 5 metres (17 feet) high, and a television antenna atop the tower gives it a total elevation of 324 metres (1,063 feet)."]
let Liberty=["The Statue of Liberty is 151 feet tall and stands on a pedestal that is 154 feet tall, making the height of the entire sculpture 305 feet"]
let StatueUnity=["The Statue of Unity is the world's tallest statue, with a height of 182 metres (597 feet)."]
let apoinment=["To book your apointment click the following link <br>apointment.com<b/>"]
let motionlaw=["In the first law, an object will not change its motion unless a force acts on it. In the second law, the force on an object is equal to its mass times its acceleration. In the third law, when two objects interact, they apply forces to each other of equal magnitude and opposite direction"]
let firstlaw=["Newton's first law states that if a body is at rest or moving at a constant speed in a straight line, it will remain at rest or keep moving in a straight line at constant speed unless it is acted upon by a force."]
let secondlaw=["Newton's Second Law of Motion says that acceleration (gaining speed) happens when a force acts on a mass (object). ... Newton's Second Law also says that the greater the mass of the object being accelerated, the greater the amount of force needed to accelerate the object."]
let thirdlaw=["The third law of motion states that when one object exerts a force on another object, the second object instantaneously exerts a force back on the first object. These two forces are always equal in magnitude but opposite in direction."]
let biodiversity=["Biodiversity is a term used to describe the enormous variety of life on Earth.Biodiversity refers to every living thing, including plants, bacteria, animals, and humans. Scientists have estimated that there are around 8.7 million species of plants and animals in existence."]
let sky=["Sunlight reaches Earth's atmosphere and is scattered in all directions by all the gases and particles in the air. Blue light is scattered more than the other colors because it travels as shorter, smaller waves. This is why we see a blue sky most of the time."]
let earthWeight=["Earth weighs about 5.972 into 10^24 kg or 13170000000000000000000000 pounds (or 5974000000000000000000000 kilograms). Since Earth is too big to be placed on a scale, scientists use mathematics and the laws of gravity to figure out Earth's weight."]
let sunFar=["Sun is about 147.99 million km far away from Earth"]
let computerInventer=["The first computer that resembled the modern machines we see today was invented by Charles Babbage between 1833 and 1871. He developed a device, the analytical engine, and worked on it for nearly 40 years."]
let planeFly=["Airplanes fly because they are able to generate a force called Lift which normally moves the airplane upward. Lift is generated by the forward motion of the airplane through the air. This motion is produced by the Thrust of the engines."]
let poerUnit=["Unit of power is Watt"]
let inventedYou=["I am coded up by Om Wadgaonkar and  designed By Rajveer Pardeshi from 10th B"]
let riddle = ["Riddle: What has to be broken before you can use it?  <br>Answer is- An egg(<br /> "];
let newSpe=["The main factors which lead to the rise of new species are natural selection, genetic drift, geographical isolation, and mutation."]
let circuit=["A continuous and closed path of an electric current is called an electric circuit. An electric circuit consists of electric devices, a source of electricity and wires that are connected with the help of a switch."]
let emotor=["An electric motor works on the principle that when a rectangular coil is placed in a magnetic field and a current is passed through it, a force acts on the coil which rotates it continuously. Hence, electrical energy is converted into mechanical energy."]
let fleming=["When a current-carrying conductor is placed in an external magnetic field, the conductor experiences a force perpendicular to both the field and to the direction of the current flow. It was invented by John Ambrose Fleming."]
let tenetal=["Lithium and Beryllium are the metals among the first ten elements in Modern Periodic Table."]
let nonMetalic=["Nonmetals have high ionization energies and electronegativities. They are generally poor conductors of heat and electricity. Solid nonmetals are generally brittle, with little or no metallic luster. Most nonmetals have the ability to gain electrons easily."]
let dobereiner=["He was not able to prepare triads of all the known elements. All the known elements could not be arranged in the form of triads. For very low mass or for very high mass elements, the law was not holding good."]
let newland=["Newland's Law of Octaves states that when Elements are arranged in increasing order of Atomic Mass, the properties of every eighth Element starting from any Element are a repetition of the properties of the starting Element."]
let brossc=["Brass and copper are metals. When sour substances like curd are kept in brass or copper vessels , the lactic acid in curd reacts with the metals which leads to the corrosion of the vessels as well as the formation of harmful salts that cannot be consumed"]
let aqueous=["The aqueous solutions of acid conduct electricity because the acid solution have H  ions and the movement of these ions helps for the flow of electrical current through the solution."]
let coordination=["Chemical coordination takes place in animals with the help of hormones. Hormones are the chemical fluids that are secreted by the glands of the endocrine system. Hormones regulate the overall growth and development of animals."]
let iodine=["If the quantity of iodine in food is lesser than required, then the neck will swell up due to the enlargement of the thyroid gland. This deficiency disease is known as goitre. Therefore, iodized salt is advised"]
let adress=[" address of Woodridge High school is  A-8, Paithan Road, Kanchanwadi, Aurangabad, Maharashtra 431010"]
let founder=["Deepak Kothari Sir is founder of Woodridge High School"]
let principle=["Frances Rozario Maam is Principal"]
let Director=[" Samantha Kothari Maam is  Director"]
let viceprinciple=["Sonu Maam is vise principle"]

const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
const recognition = new SpeechRecognition();

function showusermsg(usermsg){
    let output = '';
    output += `<div class="chatarea-inner user">${usermsg}</div>`;
    chatareaouter.innerHTML += output;
    return chatareaouter;
}

function showchatbotmsg(chatbotmsg){
    let output = '';
    output += `<div class="chatarea-inner chatbot">${chatbotmsg}</div>`;
    chatareaouter.innerHTML += output;
    return chatareaouter;
}

function chatbotvoice(message){
    const speech = new SpeechSynthesisUtterance();
    speech.text = "What are you saying?";
    if(message.includes('who are you')){
        let finalresult = intro[Math.floor(Math.random() * intro.length)];
        speech.text = finalresult;
    }
    if(message.includes('hello'|| "hi")){
        let finalresult = hi[Math.floor(Math.random() * hi.length)];
        speech.text = finalresult;
    }
    if(message.includes('what is your name')){
        let finalresult = intro[Math.floor(Math.random() * intro.length)];
        speech.text = finalresult;
    }
    if(message.includes('fine')){
        let finalresult = help[Math.floor(Math.random() * help.length)];
        speech.text = finalresult;
    }
    if(message.includes('how are you' || 'how are you doing today')){
        let finalresult = greetings[Math.floor(Math.random() * greetings.length)];
        speech.text = finalresult;
    }
    if(message.includes('tell me something about you' || 'tell me something about your hobbies')){
        let finalresult = hobbies[Math.floor(Math.random() * hobbies.length)];
        speech.text = finalresult;
    }
    if(message.includes('what are your hobbies' || 'tell me something about your hobbies')){
        let finalresult = hobbies[Math.floor(Math.random() * hobbies.length)];
        speech.text = finalresult;
    }
    if(message.includes('pizza')){
        let finalresult = pizzas[Math.floor(Math.random() * pizzas.length)];
        speech.text = finalresult;
    }
    if(message.includes('thank you' || 'thank you so much')){
        let finalresult = thank[Math.floor(Math.random() * thank.length)];
        speech.text = finalresult;
    }
    if(message.includes('talk to you' || 'talk')){
        let finalresult = closing[Math.floor(Math.random() * closing.length)];
        speech.text = finalresult;
    }
    if(message.includes('bye' || 'goodbye')){
        let finalresult = closing[Math.floor(Math.random() * closing.length)];
        speech.text = finalresult;
    }
    if(message.includes('introduce yourself' || 'jarvis introduce yourself')){
        let finalresult = information;
        speech.text = finalresult;
    }
    if(message.includes('show list' || 'what')){
        let finalresult = showlist;
        speech.text = finalresult;
    }
    if(message.includes('ok' || 'fine')){
        let finalresult = ok;
        speech.text = finalresult;
    }
    if(message.includes('live' || 'fine')){
        let finalresult = live;
        speech.text = finalresult;
    }
    if(message.includes('game' || 'fine')){
        let finalresult = game;
        speech.text = finalresult;
    }
    if(message.includes('video game' || 'fine')){
        let finalresult = videogame;
        speech.text = finalresult;
    }
    if(message.includes(' Burj Khalifa' || 'fine')){
        let finalresult = bhurjkhalfa;
        speech.text = finalresult;
    }
    if(message.includes(' Eiffel Tower' || 'fine')){
        let finalresult = eiffel;
        speech.text = finalresult;
    }
    if(message.includes('Statue of Liberty' || 'fine')){
        let finalresult = Liberty;
        speech.text = finalresult;
    }
    if(message.includes('tallest statue' || 'fine')){
        let finalresult = StatueUnity;
        speech.text = finalresult;
    }
    if(message.includes('Statue of Unity' || 'fine')){
        let finalresult = StatueUnity;
        speech.text = finalresult;
    }
    if(message.includes('book' || 'fine')){
        let finalresult = apoinment;
        speech.text = finalresult;
    }
    if(message.includes('laws of motion' || 'fine')){
        let finalresult = motionlaw;
        speech.text = finalresult;
    }
    if(message.includes('first law of motion' || 'fine')){
        let finalresult = firstlaw;
        speech.text = finalresult;
    }
    if(message.includes('first law of the motion' || 'fine')){
        let finalresult = firstlaw;
        speech.text = finalresult;
    }
    if(message.includes('second law of motion' || 'fine')){
        let finalresult = secondlaw;
        speech.text = finalresult;
    }
    if(message.includes('second law of the motion' || 'fine')){
        let finalresult = secondlaw;
        speech.text = finalresult;
    }
    if(message.includes('third law of motion' || 'fine')){
        let finalresult = thirdlaw;
        speech.text = finalresult;
    }
    if(message.includes('third law of the motion' || 'fine')){
        let finalresult = thirdlaw;
        speech.text = finalresult;
    }
    if(message.includes('biodiversity' || 'fine')){
        let finalresult = biodiversity;
        speech.text = finalresult;
    }
    if(message.includes('sky' || 'fine')){
        let finalresult = sky;
        speech.text = finalresult;
    }
    if(message.includes('weight of earth' || 'fine')){
        let finalresult = earthWeight;
        speech.text = finalresult;
    }
    if(message.includes('earth weight' || 'fine')){
        let finalresult = earthWeight;
        speech.text = finalresult;
    }
    if(message.includes('earth weigh' || 'fine')){
        let finalresult = earthWeight;
        speech.text = finalresult;
    }
    if(message.includes('sun far' || 'fine')){
        let finalresult = sunFar;
        speech.text = finalresult;
    }
    if(message.includes('sun from earth' || 'fine')){
        let finalresult = sunFar;
        speech.text = finalresult;
    }
    if(message.includes('invented computer' || 'fine')){
        let finalresult = computerInventer;
        speech.text = finalresult;
    }
    if(message.includes('airoplane fly' || 'fine')){
        let finalresult = planeFly;
        speech.text = finalresult;
    }
    if(message.includes('airoplane fly' || 'fine')){
        let finalresult = planeFly;
        speech.text = finalresult;
    }
    if(message.includes('aeroplane fly' || 'fine')){
        let finalresult = planeFly;
        speech.text = finalresult;
    }
    if(message.includes('unit of power' || 'fine')){
        let finalresult = poerUnit;
        speech.text = finalresult;
    }
    if(message.includes('powers unit' || 'fine')){
        let finalresult = poerUnit;
        speech.text = finalresult;
    }
    if(message.includes('power unit' || 'fine')){
        let finalresult = poerUnit;
        speech.text = finalresult;
    }
    if(message.includes('power SI unit' || 'fine')){
        let finalresult = poerUnit;
        speech.text = finalresult;
    }
    if(message.includes('made you' || 'fine')){
        let finalresult = inventedYou;
        speech.text = finalresult;
    }
    if(message.includes('can' || 'fine')){
        let finalresult = riddle;
        speech.text = finalresult;
    }
    if(message.includes('new spicies' || 'fine')){
        let finalresult = newSpe;
        speech.text = finalresult;
    }
    if(message.includes('what factor could lead to rise of new species' || 'fine')){
        let finalresult = newSpe;
        speech.text = finalresult;
    }
    if(message.includes('what does an electric circuit mean' || 'fine')){
        let finalresult = circuit;
        speech.text = finalresult;
    }
    if(message.includes('electric motor' || 'fine')){
        let finalresult = emotor;
        speech.text = finalresult;
    }
    if(message.includes('fleming' || 'fine')){
        let finalresult = fleming;
        speech.text = finalresult;
    }
    if(message.includes('Fleming' || 'fine')){
        let finalresult = fleming;
        speech.text = finalresult;
    }
    if(message.includes('metal' || 'fine')){
        let finalresult = tenetal;
        speech.text = finalresult;
    }
    if(message.includes('non metallic' || 'fine')){
        let finalresult = nonMetalic;
        speech.text = finalresult;
    }
    if(message.includes('traid' || 'fine')){
        let finalresult = dobereiner;
        speech.text = finalresult;
    }
    if(message.includes('drawbacks of dobereiner triad' || 'fine')){
        let finalresult = dobereiner;
        speech.text = finalresult;
    }
    if(message.includes('drawback of dobereiner triad' || 'fine')){
        let finalresult = dobereiner;
        speech.text = finalresult;
    }
    if(message.includes('drawback of dobereiners triad' || 'fine')){
        let finalresult = dobereiner;
        speech.text = finalresult;
    }
    if(message.includes('Triad' || 'fine')){
        let finalresult = dobereiner;
        speech.text = finalresult;
    }
    if(message.includes('law of Octave' || 'fine')){
        let finalresult = newland;
        speech.text = finalresult;
    }
    if(message.includes('law of Octaves' || 'fine')){
        let finalresult = newland;
        speech.text = finalresult;
    }
    if(message.includes('newlands law of octaves' || 'fine')){
        let finalresult = newland;
        speech.text = finalresult;
    }
    if(message.includes('why should curd and sour substances not be kept in brass and copper vessels in short answer' || 'fine')){
        let finalresult = brossc;
        speech.text = finalresult;
    }
    if(message.includes('why should curd and sour substances not be kept in brass and copper vessels in short answer' || 'fine')){
        let finalresult = brossc;
        speech.text = finalresult;
    }
    if(message.includes('vessels' || 'fine')){
        let finalresult = brossc;
        speech.text = finalresult;
    }
    if(message.includes('aqueous' || 'fine')){
        let finalresult = aqueous;
        speech.text = finalresult;
    }
    if(message.includes('coordination' || 'fine')){
        let finalresult = coordination;
        speech.text = finalresult;
    }
    if(message.includes('iodine' || 'fine')){
        let finalresult = iodine;
        speech.text = finalresult;
    }
    if(message.includes('iodised' || 'fine')){
        let finalresult = iodine;
        speech.text = finalresult;
    }
    if(message.includes('address' || 'fine')){
        let finalresult = adress;
        speech.text = finalresult;
    }
    if(message.includes('where' || 'fine')){
        let finalresult = adress;
        speech.text = finalresult;
    }
    if(message.includes('founder' || 'fine')){
        let finalresult = founder;
        speech.text = finalresult;
    }
    if(message.includes('Founder' || 'fine')){
        let finalresult = founder;
        speech.text = finalresult;
    }
    if(message.includes('Director' || 'fine')){
        let finalresult = Director;
        speech.text = finalresult;
    }
    if(message.includes('director' || 'fine')){
        let finalresult = Director;
        speech.text = finalresult;
    }
    if(message.includes('vice' || 'fine')){
        let finalresult = viceprinciple;
        speech.text = finalresult;
    }
    if(message.includes('Vice' || 'fine')){
        let finalresult = viceprinciple;
        speech.text = finalresult;
    }
    if(message.includes('principal' || 'fine')){
        let finalresult = principle;
        speech.text = finalresult;
    }
    if(message.includes('Principal' || 'fine')){
        let finalresult = principle;
        speech.text = finalresult;
    }







    
    window.speechSynthesis.speak(speech);
    chatareamain.appendChild(showchatbotmsg(speech.text));
    
}


recognition.onresult=function(e){
    let resultIndex = e.resultIndex;
    let transcript = e.results[resultIndex][0].transcript;
    chatareamain.appendChild(showusermsg(transcript));
    chatbotvoice(transcript);
    console.log(transcript);
}
recognition.onend=function(){
    mic.style.background="#ff3b3b";
}

function colorChange(){
    
}

mic.addEventListener("click", function(){
    mic.style.background='#39c81f';
    recognition.start();
    console.log("Activated");
})

//By Om Wadgaonkar And Rajveer Pardesi :)